### PR TITLE
deduce type: adding support for bool

### PR DESCRIPTION
**Pull request by galeone**

### CODE REVIEW

**Comment by serizba** [comment]
Hi @galeone 

Thanks for your work. Did you check that your modification actually works?

Your modification would be interesting to directly create boolean tensors from c++ bool data structures. Nevertheless, the `tensor` constructor uses `std::vector`, which is specialized for `std::vector<bool>`. From the [documentation](http://www.cplusplus.com/reference/vector/vector-bool/):

> The specialization has the same member functions as the unspecialized vector, except data, emplace, and emplace_back, that are not present in this specialization.

I tried your code in my computer and I couldn't make it work, as I can't call `values.data()` on a vector of bools.

Perhaps the solution would be to create specialized constructors that accept a `std::vector<bool>`, convert them to `unsigned char` and then call the correct funtion.

Thanks!
Sergio

**Comment by galeone** [comment]
Uhm that's really strange - I'm using that code right now and it's working fine.

I wrapped your library in an unreal engine plugin, using it in this way (my wraper name is `TFTensor`)

```cpp
template <typename T> TArray<T> TFTensor::Data() const {
    auto data = _tensor->get_data<T>();
    TArray<T> ret;
    ret.SetNumUninitialized(data.size());
    for (SIZE_T i = 0; i < data.size(); ++i) {
        ret[i] = data[i];
    }
    return ret;
}
```

I also defined the operator overloading for `==` and `!=` and when I used it in this way

```cpp
        It("It should be possiblie to compare the tensors", [this] {
            TFTensor x{1.}, y{2.};

            auto no = x == y;
            auto yes = x != y;

            TestTrue("x == y is false", !no.Data<bool>()[0]);
            TestTrue("x != y is true", yes.Data<bool>()[0]);
        });
```

It's working fine

```

**Comment by serizba** [comment]
Interesting,

Did you try to create a tensor directly from boolean data? Like:
```c++
auto t = cppflow::tensor({true, true, false});
```

**Comment by galeone** [comment]
In that case, effectively, it doesn't work because std::vector<bool> has no .data. :exploding_head:

**Comment by serizba** [comment]
Exactly hahaha 

I guess that to make it work on that case we would need to do more changes :disappointed:.

**Pull request closed without merging**
