### PR TITLE
Cppflow2 context

### PR DESCRIPTION
**Pull request by ljn917**
- TF_TString for TF 2.4
- context.h is significantly changed to add thread-safety and user-defined `TFE_ContextOptions`

### CODE REVIEW

**Comment by ljn917** [comment]
I also want to separate `TF_Status` from `context`, but not sure about your opinion.

The other thing I am not sure is what is the best solution if multiple threads want to run one model.

**Comment by ljn917** [comment]
@serizba Please point out if I am wrong. It seems `EagerContext` is thread-safe, which means I only need to protect `tf_status` instead of the whole `context` object. If this is the case, I need to change the PR.

**Comment by serizba** [comment]
Hi @ljn917 !

Thanks for your help, this looks great!
I am not pretty sure about how thread-safe is everything as I think that you have more idea than me about it. Then, choose the option that you think is best, and I will accept it :blush:

Thanks for your help!

**Comment by ljn917** [comment]
@serizba I added a small test for multi-threading. It gives the correct results with the current version. ThreadSanitizer gave tons of false positives, so I didn't enable it. From TF source code, I believe `tensorflow::EagerContext` is thread-safe. In graph mode, graph construction is not thread-safe, but in eager mode, it seems op creation and execution is also thread-safe.

At this time, `TF_Status` is `thread_local`, but `context` is global. One can set the global `cppflow::global_context` to change the runtime environment, e.g. memory limits and devices. In the future, a context manager is needed, if users want to have thread-specific context, e.g. CPU only threads vs GPU threads.

**Comment by serizba** [comment]
@ljn917 That's perfect, great work :+1: 

I think for the moment is more than enough to cover the common requisites of the users.

Thanks!

**Pull request merged**
