### PR TITLE
Add dtype to tensor to_string()

### PR DESCRIPTION
**Pull request by MarkJGx**

### CODE REVIEW

**Comment by serizba** [comment]
Hi @MarkJGx 

Thanks for your contribution. I think is a good idea to add `dtype` to the string representation. Nevertheless, I think it is not neccessary to use `string_format` to create a string for the `dtype`. You can create the placeholder string with the `dtype` directly included. Something like this:

```C++
auto res_tensor = string_format({t.shape(), t}, "(tensor: shape=%s, dtype="+ to_string(t.dtype()) + ", data=\n%s)");
```
Also, I would prefer to have the `dtype` between the shape and the data :).

What do you think?

**Comment by MarkJGx** [comment]
It's your library, so your decision. Although I'm in no rush to edit my PR. This thing is a joy to work with compared to the C API. Great work and thank you.

**Comment by serizba** [comment]
Then, can you modify it and squash the commits?

I'll accept it afterwards

**Comment by serizba** [comment]
I finally changed it my self. Thanks!

**Pull request closed without merging**
